name:  datavis_image_exptt
channels:
 - defaults
 - conda-forge
dependencies:
 - scipy
 - pandas
 - numpy
 - ipykernel
 - matplotlib
 - opencv
 - python-dotenv
 - scikit-learn
 - scikit-image
 - ipywidgets
